### ISSUE TITLE
Will this work with 1.21.3?

### ISSUE THREAD

**Issue by cecaelion** [Kim-Lan/protect-animals#3]
Hello! This is an excellent mod that players on my server enjoy having. We're planning a 1.21.3 update in the near future, and I wanted to know if the current version of the mod will work with 1.21.3? If not, do you have plans to make a 1.21.3 version of the mod?

Thanks!

**Comment by Kim-Lan** [comment]
Hi, thanks for enjoying my mod! As requested, I just updated the mod to 1.21.3: https://modrinth.com/mod/protect-animals/version/1.2.0
